# Generated by Django 2.0.6 on 2018-06-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='content2',
        ),
    ]
